[package]
name = "hf_xet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hf_xet"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.3", features = ["extension-module", "abi3-py37"] }

data = { path = "../data" }
utils = { path = "../utils" }
tokio = { version = "1.36", features = ["full"] }
parutils = { path = "../parutils" }
tracing = "0.1.*"
tracing-subscriber = { version = "0.3", features = ["json", "tracing-log", "env-filter"] }
